# Generated by Django 6.0.6 on 2026-07-11 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='quantity',
        ),
        migrations.AddField(
            model_name='category',
            name='specification_template',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='device',
            name='specifications',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
