# Generated by Django 6.0.6 on 2026-07-13 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_remove_device_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
