# Generated by Django 6.0.6 on 2026-07-17 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_device_quantity'),
        ('rental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.cart')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.device')),
            ],
            options={
                'unique_together': {('cart', 'device')},
            },
        ),
        migrations.CreateModel(
            name='RentalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=50)),
                ('discipline', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('approved', 'Подтверждена'), ('rejected', 'Отклонена')], default='pending', max_length=20)),
                ('pdf', models.FileField(blank=True, null=True, upload_to='requests/pdf/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentalRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('return_date', models.DateField()),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.device')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.rentalrequest')),
            ],
        ),
        migrations.DeleteModel(
            name='Rental',
        ),
    ]
